project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  favicon: images/favicon.ico
  site-url: http://mxochicale.github.io/tools/quarto-test
  search: false
  twitter-card:
    creator: "@mxochicale"
    card-style: summary
    image: favicon_org.png
  open-graph:
    image: favicon_org.png

