project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  favicon: favicon.svg
  site-url: http://mxochicale.github.io/tools/quarto/slides-template01
  search: false
  twitter-card:
    creator: "@mxochicale"
    card-style: summary
    image: images/favicon_org.png
  open-graph:
    image: images/favicon_org.png

