name: Quarto Publish

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto --version

      - name: Publish to GitHub Pages t00
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: quarto/slides-template00
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Pages t01
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: quarto/slides-template01
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

