name: Deploy Quarto Slides

on:
  push:
    branches:
      - main
      - 28-quarto-js-and-ci
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  deploy-slides:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/quarto/template/Gemfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install and Build
        working-directory: ./quarto/template
        run: >-
            JEKYLL_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            JEKYLL_ENV=production
            bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./quarto/template/_site
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
